load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["contentHolder.go"],
    importpath = "github.com/DiTo04/spexflix/content/content",
    visibility = ["//visibility:public"],
)
