// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	LoginRequest
	LoginReply
	AuRequest
	AuReply
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	IsAuthenticated bool   `protobuf:"varint,1,opt,name=isAuthenticated" json:"isAuthenticated,omitempty"`
	SessionToken    string `protobuf:"bytes,2,opt,name=sessionToken" json:"sessionToken,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginReply) GetIsAuthenticated() bool {
	if m != nil {
		return m.IsAuthenticated
	}
	return false
}

func (m *LoginReply) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

type AuRequest struct {
	SessionToken string `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
}

func (m *AuRequest) Reset()                    { *m = AuRequest{} }
func (m *AuRequest) String() string            { return proto.CompactTextString(m) }
func (*AuRequest) ProtoMessage()               {}
func (*AuRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

type AuReply struct {
	IsAuthenticated bool   `protobuf:"varint,1,opt,name=isAuthenticated" json:"isAuthenticated,omitempty"`
	Username        string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *AuReply) Reset()                    { *m = AuReply{} }
func (m *AuReply) String() string            { return proto.CompactTextString(m) }
func (*AuReply) ProtoMessage()               {}
func (*AuReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuReply) GetIsAuthenticated() bool {
	if m != nil {
		return m.IsAuthenticated
	}
	return false
}

func (m *AuReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "LoginReply")
	proto.RegisterType((*AuRequest)(nil), "AuRequest")
	proto.RegisterType((*AuReply)(nil), "AuReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for authentication service

type AuthenticationClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	Authenticate(ctx context.Context, in *AuRequest, opts ...grpc.CallOption) (*AuReply, error)
}

type authenticationClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationClient(cc *grpc.ClientConn) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/authentication/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) Authenticate(ctx context.Context, in *AuRequest, opts ...grpc.CallOption) (*AuReply, error) {
	out := new(AuReply)
	err := grpc.Invoke(ctx, "/authentication/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for authentication service

type AuthenticationServer interface {
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	Authenticate(context.Context, *AuRequest) (*AuReply, error)
}

func RegisterAuthenticationServer(s *grpc.Server, srv AuthenticationServer) {
	s.RegisterService(&_Authentication_serviceDesc, srv)
}

func _Authentication_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authentication/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authentication/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Authenticate(ctx, req.(*AuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Authentication_Login_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _Authentication_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe3, 0xe2, 0xf1, 0xc9, 0x4f, 0xcf, 0xcc, 0x0b, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe2, 0xe2, 0x28, 0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc,
	0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0x05, 0x89, 0xc5, 0xc5,
	0xe5, 0xf9, 0x45, 0x29, 0x12, 0x4c, 0x10, 0x39, 0x18, 0x5f, 0x29, 0x8a, 0x8b, 0x0b, 0x6a, 0x4e,
	0x41, 0x4e, 0xa5, 0x90, 0x06, 0x17, 0x7f, 0x66, 0xb1, 0x63, 0x69, 0x49, 0x46, 0x6a, 0x5e, 0x49,
	0x66, 0x72, 0x62, 0x49, 0x6a, 0x0a, 0xd8, 0x30, 0x8e, 0x20, 0x74, 0x61, 0x21, 0x25, 0x2e, 0x9e,
	0xe2, 0xd4, 0xe2, 0xe2, 0xcc, 0xfc, 0xbc, 0x90, 0xfc, 0xec, 0xd4, 0x3c, 0xa8, 0xb9, 0x28, 0x62,
	0x4a, 0xfa, 0x5c, 0x9c, 0x8e, 0xa5, 0x30, 0x07, 0xa2, 0x6b, 0x60, 0xc4, 0xa2, 0xc1, 0x9f, 0x8b,
	0x1d, 0xa4, 0x81, 0x34, 0x97, 0x20, 0xfb, 0x9c, 0x09, 0xd5, 0xe7, 0x46, 0xf1, 0x5c, 0x7c, 0x48,
	0x8a, 0x33, 0xf3, 0xf3, 0x84, 0x54, 0xb9, 0x58, 0xc1, 0xfe, 0x15, 0xe2, 0xd5, 0x43, 0x0e, 0x3f,
	0x29, 0x6e, 0x3d, 0x44, 0x30, 0x28, 0x31, 0x08, 0xa9, 0x71, 0xf1, 0x20, 0xdb, 0x22, 0xc4, 0xa5,
	0x07, 0xf7, 0x89, 0x14, 0x87, 0x1e, 0xd4, 0x91, 0x4a, 0x0c, 0x49, 0x6c, 0xe0, 0xd8, 0x30, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x24, 0x32, 0x49, 0x9a, 0x01, 0x00, 0x00,
}
