sudo: required
dist: trusty
language:
  - java
os:
  - linux
jdk:
  - oraclejdk8  # Building Bazel requires JDK8.
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
      - sourceline: 'deb [arch=amd64] http://packages.cloud.google.com/apt cloud-sdk-trusty main'
        key_url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    packages:
      - bazel
      - google-cloud-sdk
      - kubectl

before_install:
  # Log into gcloud
  - echo -n "${GCLOUD_KEY}" | base64 -d > keyfile.json
  - gcloud auth activate-service-account --key-file keyfile.json
  - docker login -u _json_key -p "$(cat keyfile.json)" https://gcr.io
  - rm -f keyfile.json
  - gcloud config set core/project spexflix
  - gcloud config set compute/zone europe-west1-b
  - gcloud container clusters get-credentials develop

script:
  # Check our installs.
  - bazel version
  - gcloud version
  - kubectl version

  # Check that all of our tools and samples build
  - bazel clean && bazel build //...
  # Check that all of our tests pass
  - bazel test //...
  
deploy:
  - provider: script
    script: bazel run //k8s:canary.apply
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bazel run //k8s:production.apply
    skip_cleanup: true
    on:
      tags: true
