load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["client.go"],
    importpath = "github.com/DiTo04/spexflix/front-end/content_client",
    visibility = ["//visibility:public"],
    deps = ["//common/codecs:go_default_library"],
)
