apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
      kubernetes.io/ingress.global-static-ip-name: k8s-fw-spexflix-production-main-ingress--7925afce811f0a15
      kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
    - secretName: spexflix-se-tls
  rules:
  - host: theodor.spexflix.se
    http:
      paths:
      - backend:
          serviceName: theodor
          servicePort: web
  - host: spexflix.se
    http:
      paths:
      - path: /api/v1/*
        backend:
          serviceName: api
          servicePort: web
      - path: /*
        backend:
          serviceName: web
          servicePort: web
