apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: content-production
  labels:
    app: content
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content
      env: production
  template:
    metadata:
      labels:
        app: content
        env: production
    spec:
      containers:
      - name: content
        image: gcr.io/spexflix/content:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: rest
        resources:
          requests:
            memory: "5Mi"
            cpu: "100m"
          limits:
            memory: "10Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: rest
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /healthz
            port: rest
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15
        env:
        - name: AUTHENTICATION_SERVER
          value: "authentication"
        - name: AUTHENTICATION_PORT
          value: "8080"
        - name: SERVER_PORT
          value: "8080"
---
kind: Service
apiVersion: v1
metadata:
  name: content
spec:
  selector:
    app: content
  ports:
  - name: rest
    protocol: TCP
    port: 8080
    targetPort: rest
