apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: content-deployment
  labels:
    app: content
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
      - name: content
        image: docker.io/tennander/spexflix-content
        ports:
        - containerPort: 8000
          name: rest
        env:
        - name: AUTHENTICATION_SERVER
          value: "authentication"
        - name: AUTHENTICATION_PORT
          value: "31117"
---
kind: Service
apiVersion: v1
metadata:
  name: content
spec:
  selector:
    app: content
  ports:
  - name: rest
    protocol: TCP
    port: 8000
    targetPort: rest
