apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: tennander/spexflix-gateway
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: web
        env:
        - name: AUTHENTICATION_SERVER
          value: "authentication"
        - name: AUTHENTICATION_PORT
          value: "8080"
        - name: CONTENT_SERVER
          value: "content"
        - name: CONTENT_PORT
          value: "8080"
        - name: PORT
          value: "8080"
---
kind: Service
apiVersion: v1
metadata:
  name: front-end
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: web
