apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: users-production
  labels:
    app: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
      env: production
  template:
    metadata:
      labels:
        app: users
        env: production
    spec:
      containers:
      - name: users
        image: gcr.io/spexflix/users:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
        resources:
          requests:
            memory: "5Mi"
            cpu: "100m"
          limits:
            memory: "10Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: web
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /healthz
            port: web
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: PORT
          value: "8080"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/cloudsql/credentials.json"
        - name: DB_NAME
          value: "users"
        - name: DB_INSTANCE_CONNECTION_NAME
          value: "spexflix:europe-west1:spexflix-users"
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
---
kind: Service
apiVersion: v1
metadata:
  name: users
spec:
  selector:
    app: users
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: web