apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: theodor
  labels:
    app: theodor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theodor
  template:
    metadata:
      labels:
        app: theodor
    spec:
      containers:
      - name: web
        image: gcr.io/spexflix/theodor:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "250m"
---
kind: Service
apiVersion: v1
metadata:
  name: theodor
spec:
  selector:
    app: theodor
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: web