load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "mockHttpClient.go",
        "nopCloser.go",
    ],
    importpath = "github.com/DiTo04/spexflix/common/mocks",
    visibility = ["//visibility:public"],
)
